
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Lisbon"      
    rebase-strategy: "auto"
    reviewers:
      - "njasm"
      - "njasm-f3"
    # Prefix all commit messages with "gomod" include a list of updated dependencies
    commit-message:
      prefix: "gomod"
      include: "scope"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Lisbon"            
    reviewers:
      - "njasm"
      - "njasm-f3"
    # Prefix all commit messages with "github actions"
    # include a list of updated dependencies
    commit-message:
      prefix: "github actions"
      include: "scope"         