version: "3.9"

services:
  clerk:
    container_name: clerk
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - RUNNING_LOCAL=$${RUNNING_LOCAL:true}
      - CONSUL_HTTP_ADDR=consul-server1:8500
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - consul
    depends_on:
      - consul1
      - consul2
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
      restart_policy:
        condition: on-failure

  consul1:
    container_name: consul-server1
    image: hashicorp/consul:1.11.5
    restart: always
    volumes:
      - ./resources/consul/server1.json:/consul/config/server1.json:ro
      - ./resources/consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=2"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 128M

  consul2:
    container_name: consul-server2
    image: hashicorp/consul:1.11.5
    restart: always
    volumes:
      - ./resources/consul/server2.json:/consul/config/server2.json:ro
      - ./resources/consul/certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=2"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 128M

  # consul-client:
  #   image: hashicorp/consul:1.11.5
  #   container_name: consul-client
  #   restart: always
  #   volumes:
  #     - ./resources/consul/client.json:/consul/config/client.json:ro
  #     - ./resources/consul/certs/:/consul/config/certs/:ro     
  #   networks:
  #     - consul
  #   command: "agent"

  # Define web service 
  web:
    image: nicholasjackson/fake-service:v0.23.1
    labels:
      - com.github.njasm.clerk.register=true  # true, false, Should register this service? 
      - com.github.njasm.clerk.name=basic-web-service-name # define service name
      - com.github.njasm.clerk.tags=primary,test
      - com.github.njasm.clerk.attributes=region:eu-west-1,env:staging
      # Consul HTTP check
      - com.github.njasm.clerk.consul.check.http=/health
      - com.github.njasm.clerk.consul.check.interval=10s  # optional, Consul default used otherwise
      - com.github.njasm.clerk.consul.check.timout=2s     # optional, Consul default used otherwise
      - com.github.njasm.clerk.consul.check.method=GET 	# optional, Consul default used otherwise
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      NAME: "web"
      SERVER_TYPE: "http"
      MESSAGE: "Hello World"
      HEALTH_CHECK_RESPONSE_CODE: "200"
      #UPSTREAM_URIS: "http://localhost:9091"
      #CONSUL_SERVER: 10.5.0.2
      #CONSUL_DATACENTER: "dc1"
      #CENTRAL_CONFIG_DIR: /central
      #SERVICE_ID: "web-v1"
    #volumes:
    #  - "./service_config/web_v1.hcl:/config/web_v1.hcl"
    #  - "./central_config:/central"
    networks:
      - consul
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M

  # Define internal, no exported ports service
  web-no-ports-exported:
    image: nicholasjackson/fake-service:v0.23.1
    labels:
      - com.github.njasm.clerk.register=true  # true, false, Should register this service? 
      - com.github.njasm.clerk.ports=9091/tcp  # ports to register in the service. override any exported ports definitions
      - com.github.njasm.clerk.tags=no-ports-exported
      - com.github.njasm.clerk.attributes=region:eu-west-1,env:staging
      # Consul HTTP check
      - com.github.njasm.clerk.consul.check.http=/health
      - com.github.njasm.clerk.consul.check.interval=10s  # optional, Consul default used otherwise
      - com.github.njasm.clerk.consul.check.timout=2s     # optional, Consul default used otherwise
      - com.github.njasm.clerk.consul.check.method=GET 	# optional, Consul default used otherwise
    environment:
      LISTEN_ADDR: 0.0.0.0:9091
      NAME: "web"
      SERVER_TYPE: "http"
      MESSAGE: "Hello World"
      HEALTH_CHECK_RESPONSE_CODE: "200"
    networks:
      - consul
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M

  web-grpc-no-register:
    image: nicholasjackson/fake-service:v0.23.1
    labels:
      - com.github.njasm.clerk.register=false  # true, false, Should register this service? 
    environment:
      LISTEN_ADDR: 0.0.0.0:9095
      NAME: "web-grppc"
      SERVER_TYPE: "grpc"
      MESSAGE: "Hello World gRPC"
      HEALTH_CHECK_RESPONSE_CODE: "200"
    networks:
      - consul
    ports:
      - "9095:9095"      

networks:
  consul:
    driver: bridge
