name: CI
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request: {}

jobs:
  # TODO: drop it when GitHub supports its by itself
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  run-tests:
    name: ubuntu
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go: [ 1.18.0, 1.18.1, 1.18.2 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run Tests all
        run: make test-all

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.txt
          outfile: coverage.lcov

      - name: Code Coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
          flag-name: run-${{ matrix.os }}-ubuntu-latest
          parallel: true

  code-coverage:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  ci-pass:
    name: 'ci-pass'
    runs-on: "ubuntu-latest"
    needs: run-tests
    steps:
      - name: "Merge into master"
        run: exit 0
